// "use client";
// import "bootstrap/dist/css/bootstrap.min.css";
// import { Provider } from "react-redux";
// import { store } from "../redux/store";
// import "react-toastify/dist/ReactToastify.css";
// import Header from "@/components/Header";

// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }) {
//   return (
//     <html>
//       <body>
//         <div>
//           {/* <Header/>
//           <Provider store={store}>
//             {children}
//             </Provider> */}

//             <Provider>
//         <Header />

//         <main style={{ marginTop: "70px" }}>
//           {children}
//         </main>
//         </Provider>
//         </div>

//       </body>
//     </html>
//   );
// }

import "bootstrap/dist/css/bootstrap.min.css";
import Header from "../components/Header";
import Providers from "./providers";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main>{children}</main>
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}

